import Head from 'next/head'
import {BiUserPlus} from "react-icons/bi"


export default function Header() {
    return (
        <>
        <Head>
        <title>CRUD Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1 className='text-xl md:text-5xl text-center font-bold py-10'> Utilisateur Management</h1>
        <div className='container mx-auto flex justify-between py- border-b'>
            <div className='left flex gap-3'>
                <button className='flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-grary-50 hover:border-indigo-500 hover:text-gray-800'>Ajouter un Utilisateur<span className='px-1'><BiUserPlus size={23}></BiUserPlus></span></button>
            </div>
            </div>
        </>
    )
}